# Generated by Django 3.1.4 on 2020-12-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adm_staff',
            name='ph_number',
            field=models.CharField(max_length=12),
        ),
    ]
