# Generated by Django 3.1.4 on 2020-12-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_t_p_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=25)),
                ('DESIGNATION', models.CharField(max_length=50)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('PH_NUMBER', models.CharField(max_length=12)),
            ],
        ),
    ]
