# Generated by Django 3.1.4 on 2020-12-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20201212_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='FEATURED',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
