# Generated by Django 3.1.4 on 2020-12-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alumni_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='BATCH',
            field=models.CharField(default='default', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adm_staff',
            name='ph_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='PH_NUMBER',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='t_p_staff',
            name='Ph_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
