# Generated by Django 3.1.4 on 2020-12-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20201212_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adm_staff',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='PROFILE_PIC',
        ),
        migrations.RemoveField(
            model_name='t_p_staff',
            name='Profile_pic',
        ),
    ]
