# Generated by Django 3.1.4 on 2020-12-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20201212_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adm_Staff',
        ),
        migrations.DeleteModel(
            name='Alumni',
        ),
        migrations.DeleteModel(
            name='T_P_Staff',
        ),
    ]
