# Generated by Django 3.1.4 on 2020-12-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('Enrollment_No', models.CharField(max_length=120)),
                ('Ph_No', models.CharField(max_length=120)),
                ('CGPA', models.CharField(max_length=120)),
                ('Percentage_in_10th', models.CharField(max_length=120)),
                ('Percentage_in_12th', models.CharField(max_length=120)),
                ('Branch', models.CharField(max_length=120)),
                ('Semester', models.CharField(max_length=120)),
                ('Batch', models.CharField(max_length=120)),
            ],
        ),
    ]
