# Generated by Django 3.1.4 on 2020-12-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_branch', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='register_model',
            name='Branch',
        ),
        migrations.AddField(
            model_name='register_model',
            name='Branch',
            field=models.ManyToManyField(to='members.Branch'),
        ),
    ]
