# Generated by Django 3.1.4 on 2020-12-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20201213_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_model',
            name='Semester',
            field=models.IntegerField(),
        ),
    ]
