# Generated by Django 3.1.4 on 2020-12-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20201213_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_model',
            name='Branch',
        ),
        migrations.AddField(
            model_name='register_model',
            name='Branch',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
    ]
