# Generated by Django 3.1.4 on 2020-12-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20201213_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_model',
            name='Email',
            field=models.EmailField(default='default', max_length=254),
            preserve_default=False,
        ),
    ]
