# Generated by Django 3.1.4 on 2020-12-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20201214_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_model',
            name='author',
        ),
    ]
