# Generated by Django 3.1.4 on 2020-12-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_register_model_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_model',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Register_Model',
        ),
    ]
